// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight_state_3.proto

package io.confluent.demo.aircraft.protobuf.pojo;

public final class FlightState3 {
  private FlightState3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlightStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.demo.flights.protobuf.pojo.FlightState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
     * </pre>
     *
     * <code>string callsign = 2;</code>
     * @return The callsign.
     */
    java.lang.String getCallsign();
    /**
     * <pre>
     * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
     * </pre>
     *
     * <code>string callsign = 2;</code>
     * @return The bytes for callsign.
     */
    com.google.protobuf.ByteString
        getCallsignBytes();

    /**
     * <pre>
     * Country name inferred from the ICAO 24-bit address.
     * </pre>
     *
     * <code>string origin_country = 3;</code>
     * @return The originCountry.
     */
    java.lang.String getOriginCountry();
    /**
     * <pre>
     * Country name inferred from the ICAO 24-bit address.
     * </pre>
     *
     * <code>string origin_country = 3;</code>
     * @return The bytes for originCountry.
     */
    com.google.protobuf.ByteString
        getOriginCountryBytes();

    /**
     * <pre>
     * Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.
     * </pre>
     *
     * <code>double time_position = 4;</code>
     * @return The timePosition.
     */
    double getTimePosition();

    /**
     * <pre>
     * Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.
     * </pre>
     *
     * <code>int32 last_contact = 5;</code>
     * @return The lastContact.
     */
    int getLastContact();

    /**
     * <pre>
     * WGS-84 longitude in decimal degrees. Can be null.
     * </pre>
     *
     * <code>double longitude = 6;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <pre>
     * WGS-84 latitude in decimal degrees. Can be null.
     * </pre>
     *
     * <code>double latitude = 7;</code>
     * @return The latitude.
     */
    double getLatitude();
  }
  /**
   * <pre>
   * DELETE
   *string icao24 = 1; // Unique ICAO 24-bit address of the transponder in hex string representation.
   * </pre>
   *
   * Protobuf type {@code io.confluent.demo.flights.protobuf.pojo.FlightState}
   */
  public  static final class FlightState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.demo.flights.protobuf.pojo.FlightState)
      FlightStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlightState.newBuilder() to construct.
    private FlightState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlightState() {
      callsign_ = "";
      originCountry_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FlightState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlightState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              callsign_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              originCountry_ = s;
              break;
            }
            case 33: {

              timePosition_ = input.readDouble();
              break;
            }
            case 40: {

              lastContact_ = input.readInt32();
              break;
            }
            case 49: {

              longitude_ = input.readDouble();
              break;
            }
            case 57: {

              latitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.demo.aircraft.protobuf.pojo.FlightState3.internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.demo.aircraft.protobuf.pojo.FlightState3.internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState.class, io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState.Builder.class);
    }

    public static final int CALLSIGN_FIELD_NUMBER = 2;
    private volatile java.lang.Object callsign_;
    /**
     * <pre>
     * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
     * </pre>
     *
     * <code>string callsign = 2;</code>
     * @return The callsign.
     */
    public java.lang.String getCallsign() {
      java.lang.Object ref = callsign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callsign_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
     * </pre>
     *
     * <code>string callsign = 2;</code>
     * @return The bytes for callsign.
     */
    public com.google.protobuf.ByteString
        getCallsignBytes() {
      java.lang.Object ref = callsign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callsign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGIN_COUNTRY_FIELD_NUMBER = 3;
    private volatile java.lang.Object originCountry_;
    /**
     * <pre>
     * Country name inferred from the ICAO 24-bit address.
     * </pre>
     *
     * <code>string origin_country = 3;</code>
     * @return The originCountry.
     */
    public java.lang.String getOriginCountry() {
      java.lang.Object ref = originCountry_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originCountry_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Country name inferred from the ICAO 24-bit address.
     * </pre>
     *
     * <code>string origin_country = 3;</code>
     * @return The bytes for originCountry.
     */
    public com.google.protobuf.ByteString
        getOriginCountryBytes() {
      java.lang.Object ref = originCountry_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originCountry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_POSITION_FIELD_NUMBER = 4;
    private double timePosition_;
    /**
     * <pre>
     * Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.
     * </pre>
     *
     * <code>double time_position = 4;</code>
     * @return The timePosition.
     */
    public double getTimePosition() {
      return timePosition_;
    }

    public static final int LAST_CONTACT_FIELD_NUMBER = 5;
    private int lastContact_;
    /**
     * <pre>
     * Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.
     * </pre>
     *
     * <code>int32 last_contact = 5;</code>
     * @return The lastContact.
     */
    public int getLastContact() {
      return lastContact_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 6;
    private double longitude_;
    /**
     * <pre>
     * WGS-84 longitude in decimal degrees. Can be null.
     * </pre>
     *
     * <code>double longitude = 6;</code>
     * @return The longitude.
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 7;
    private double latitude_;
    /**
     * <pre>
     * WGS-84 latitude in decimal degrees. Can be null.
     * </pre>
     *
     * <code>double latitude = 7;</code>
     * @return The latitude.
     */
    public double getLatitude() {
      return latitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCallsignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, callsign_);
      }
      if (!getOriginCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, originCountry_);
      }
      if (timePosition_ != 0D) {
        output.writeDouble(4, timePosition_);
      }
      if (lastContact_ != 0) {
        output.writeInt32(5, lastContact_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(6, longitude_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(7, latitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCallsignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, callsign_);
      }
      if (!getOriginCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, originCountry_);
      }
      if (timePosition_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, timePosition_);
      }
      if (lastContact_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, lastContact_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, longitude_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, latitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState)) {
        return super.equals(obj);
      }
      io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState other = (io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState) obj;

      if (!getCallsign()
          .equals(other.getCallsign())) return false;
      if (!getOriginCountry()
          .equals(other.getOriginCountry())) return false;
      if (java.lang.Double.doubleToLongBits(getTimePosition())
          != java.lang.Double.doubleToLongBits(
              other.getTimePosition())) return false;
      if (getLastContact()
          != other.getLastContact()) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CALLSIGN_FIELD_NUMBER;
      hash = (53 * hash) + getCallsign().hashCode();
      hash = (37 * hash) + ORIGIN_COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getOriginCountry().hashCode();
      hash = (37 * hash) + TIME_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTimePosition()));
      hash = (37 * hash) + LAST_CONTACT_FIELD_NUMBER;
      hash = (53 * hash) + getLastContact();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * DELETE
     *string icao24 = 1; // Unique ICAO 24-bit address of the transponder in hex string representation.
     * </pre>
     *
     * Protobuf type {@code io.confluent.demo.flights.protobuf.pojo.FlightState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.demo.flights.protobuf.pojo.FlightState)
        io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.demo.aircraft.protobuf.pojo.FlightState3.internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.demo.aircraft.protobuf.pojo.FlightState3.internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState.class, io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState.Builder.class);
      }

      // Construct using io.confluent.demo.flights.protobuf.pojo.FlightState3.FlightState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        callsign_ = "";

        originCountry_ = "";

        timePosition_ = 0D;

        lastContact_ = 0;

        longitude_ = 0D;

        latitude_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.demo.aircraft.protobuf.pojo.FlightState3.internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_descriptor;
      }

      @java.lang.Override
      public io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState getDefaultInstanceForType() {
        return io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState build() {
        io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState buildPartial() {
        io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState result = new io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState(this);
        result.callsign_ = callsign_;
        result.originCountry_ = originCountry_;
        result.timePosition_ = timePosition_;
        result.lastContact_ = lastContact_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState) {
          return mergeFrom((io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState other) {
        if (other == io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState.getDefaultInstance()) return this;
        if (!other.getCallsign().isEmpty()) {
          callsign_ = other.callsign_;
          onChanged();
        }
        if (!other.getOriginCountry().isEmpty()) {
          originCountry_ = other.originCountry_;
          onChanged();
        }
        if (other.getTimePosition() != 0D) {
          setTimePosition(other.getTimePosition());
        }
        if (other.getLastContact() != 0) {
          setLastContact(other.getLastContact());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object callsign_ = "";
      /**
       * <pre>
       * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
       * </pre>
       *
       * <code>string callsign = 2;</code>
       * @return The callsign.
       */
      public java.lang.String getCallsign() {
        java.lang.Object ref = callsign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          callsign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
       * </pre>
       *
       * <code>string callsign = 2;</code>
       * @return The bytes for callsign.
       */
      public com.google.protobuf.ByteString
          getCallsignBytes() {
        java.lang.Object ref = callsign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          callsign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
       * </pre>
       *
       * <code>string callsign = 2;</code>
       * @param value The callsign to set.
       * @return This builder for chaining.
       */
      public Builder setCallsign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        callsign_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
       * </pre>
       *
       * <code>string callsign = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCallsign() {
        
        callsign_ = getDefaultInstance().getCallsign();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
       * </pre>
       *
       * <code>string callsign = 2;</code>
       * @param value The bytes for callsign to set.
       * @return This builder for chaining.
       */
      public Builder setCallsignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        callsign_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object originCountry_ = "";
      /**
       * <pre>
       * Country name inferred from the ICAO 24-bit address.
       * </pre>
       *
       * <code>string origin_country = 3;</code>
       * @return The originCountry.
       */
      public java.lang.String getOriginCountry() {
        java.lang.Object ref = originCountry_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          originCountry_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Country name inferred from the ICAO 24-bit address.
       * </pre>
       *
       * <code>string origin_country = 3;</code>
       * @return The bytes for originCountry.
       */
      public com.google.protobuf.ByteString
          getOriginCountryBytes() {
        java.lang.Object ref = originCountry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originCountry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Country name inferred from the ICAO 24-bit address.
       * </pre>
       *
       * <code>string origin_country = 3;</code>
       * @param value The originCountry to set.
       * @return This builder for chaining.
       */
      public Builder setOriginCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originCountry_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Country name inferred from the ICAO 24-bit address.
       * </pre>
       *
       * <code>string origin_country = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginCountry() {
        
        originCountry_ = getDefaultInstance().getOriginCountry();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Country name inferred from the ICAO 24-bit address.
       * </pre>
       *
       * <code>string origin_country = 3;</code>
       * @param value The bytes for originCountry to set.
       * @return This builder for chaining.
       */
      public Builder setOriginCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originCountry_ = value;
        onChanged();
        return this;
      }

      private double timePosition_ ;
      /**
       * <pre>
       * Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.
       * </pre>
       *
       * <code>double time_position = 4;</code>
       * @return The timePosition.
       */
      public double getTimePosition() {
        return timePosition_;
      }
      /**
       * <pre>
       * Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.
       * </pre>
       *
       * <code>double time_position = 4;</code>
       * @param value The timePosition to set.
       * @return This builder for chaining.
       */
      public Builder setTimePosition(double value) {
        
        timePosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.
       * </pre>
       *
       * <code>double time_position = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimePosition() {
        
        timePosition_ = 0D;
        onChanged();
        return this;
      }

      private int lastContact_ ;
      /**
       * <pre>
       * Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.
       * </pre>
       *
       * <code>int32 last_contact = 5;</code>
       * @return The lastContact.
       */
      public int getLastContact() {
        return lastContact_;
      }
      /**
       * <pre>
       * Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.
       * </pre>
       *
       * <code>int32 last_contact = 5;</code>
       * @param value The lastContact to set.
       * @return This builder for chaining.
       */
      public Builder setLastContact(int value) {
        
        lastContact_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.
       * </pre>
       *
       * <code>int32 last_contact = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastContact() {
        
        lastContact_ = 0;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <pre>
       * WGS-84 longitude in decimal degrees. Can be null.
       * </pre>
       *
       * <code>double longitude = 6;</code>
       * @return The longitude.
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       * WGS-84 longitude in decimal degrees. Can be null.
       * </pre>
       *
       * <code>double longitude = 6;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * WGS-84 longitude in decimal degrees. Can be null.
       * </pre>
       *
       * <code>double longitude = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <pre>
       * WGS-84 latitude in decimal degrees. Can be null.
       * </pre>
       *
       * <code>double latitude = 7;</code>
       * @return The latitude.
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       * WGS-84 latitude in decimal degrees. Can be null.
       * </pre>
       *
       * <code>double latitude = 7;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * WGS-84 latitude in decimal degrees. Can be null.
       * </pre>
       *
       * <code>double latitude = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.demo.flights.protobuf.pojo.FlightState)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.demo.flights.protobuf.pojo.FlightState)
    private static final io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState();
    }

    public static io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlightState>
        PARSER = new com.google.protobuf.AbstractParser<FlightState>() {
      @java.lang.Override
      public FlightState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlightState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlightState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlightState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.demo.aircraft.protobuf.pojo.FlightState3.FlightState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024flight_state_3.proto\022\'io.confluent.dem" +
      "o.flights.protobuf.pojo\"\211\001\n\013FlightState\022" +
      "\020\n\010callsign\030\002 \001(\t\022\026\n\016origin_country\030\003 \001(" +
      "\t\022\025\n\rtime_position\030\004 \001(\001\022\024\n\014last_contact" +
      "\030\005 \001(\005\022\021\n\tlongitude\030\006 \001(\001\022\020\n\010latitude\030\007 " +
      "\001(\001B\016B\014FlightState3b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_demo_flights_protobuf_pojo_FlightState_descriptor,
        new java.lang.String[] { "Callsign", "OriginCountry", "TimePosition", "LastContact", "Longitude", "Latitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
