package io.confluent.demo.aircraft.jsonschema.utils;

import io.confluent.demo.aircraft.jsonschema.pojo.FlightStateSchema1;
import io.confluent.demo.aircraft.jsonschema.pojo.FlightStateSchema2;
import io.confluent.demo.aircraft.jsonschema.pojo.FlightStateSchema3;

public class FlightPrettyPrint {

    public String printFlightV1(FlightStateSchema1 flight) {

        StringBuilder sb = new StringBuilder();
        sb.append("callsign (aka FLIGHT NUMBER)");
        sb.append('=');
        sb.append(((flight.getCallsign() == null)?"<null>":flight.getCallsign()));
        sb.append('\n');
        sb.append("icao24");
        sb.append('=');
        sb.append(((flight.getIcao24() == null)?"<null>":flight.getIcao24()));
        sb.append('\n');
        sb.append("originCountry");
        sb.append('=');
        sb.append(((flight.getOriginCountry() == null)?"<null>":flight.getOriginCountry()));
        sb.append('\n');
        sb.append("timePosition");
        sb.append('=');
        sb.append(((flight.getTimePosition() == null)?"<null>":flight.getTimePosition()));
        sb.append('\n');
        sb.append("lastContact");
        sb.append('=');
        sb.append(((flight.getLastContact() == null)?"<null>":flight.getLastContact()));
        sb.append('\n');
        sb.append("longitude");
        sb.append('=');
        sb.append(((flight.getLongitude() == null)?"<null>":flight.getLongitude()));
        sb.append('\n');
        sb.append("latitude");
        sb.append('=');
        sb.append(((flight.getLatitude() == null)?"<null>":flight.getLatitude()));
        sb.append('\n');
        sb.append("baroAltitude");
        sb.append('=');
        sb.append(((flight.getBaroAltitude() == null)?"<null>":flight.getBaroAltitude()));
        sb.append('\n');
        sb.append("velocity");
        sb.append('=');
        sb.append(((flight.getVelocity() == null)?"<null>":flight.getVelocity()));
        sb.append('\n');
        sb.append("trueTrack");
        sb.append('=');
        sb.append(((flight.getTrueTrack() == null)?"<null>":flight.getTrueTrack()));
        sb.append('\n');
        sb.append("verticalRate");
        sb.append('=');
        sb.append(((flight.getVerticalRate() == null)?"<null>":flight.getVerticalRate()));
        sb.append('\n');
        sb.append("geoAltitude");
        sb.append('=');
        sb.append(((flight.getGeoAltitude() == null)?"<null>":flight.getGeoAltitude()));
        sb.append('\n');
        sb.append("squawk");
        sb.append('=');
        sb.append(((flight.getSquawk() == null)?"<null>":flight.getSquawk()));
        sb.append('\n');
        sb.append("spi");
        sb.append('=');
        sb.append(((flight.getSpi() == null)?"<null>":flight.getSpi()));
        return sb.toString();
    }

    public String printFlightV2(FlightStateSchema2 flight) {

        StringBuilder sb = new StringBuilder();
        sb.append("callsign (aka FLIGHT NUMBER)");
        sb.append('=');
        sb.append(((flight.getCallsign() == null)?"<null>":flight.getCallsign()));
        sb.append('\n');
        sb.append("icao24");
        sb.append('=');
        sb.append(((flight.getIcao24() == null)?"<null>":flight.getIcao24()));
        sb.append('\n');
        sb.append("originCountry");
        sb.append('=');
        sb.append(((flight.getOriginCountry() == null)?"<null>":flight.getOriginCountry()));
        sb.append('\n');
        sb.append("timePosition");
        sb.append('=');
        sb.append(((flight.getTimePosition() == null)?"<null>":flight.getTimePosition()));
        sb.append('\n');
        sb.append("lastContact");
        sb.append('=');
        sb.append(((flight.getLastContact() == null)?"<null>":flight.getLastContact()));
        sb.append('\n');
        sb.append("longitude");
        sb.append('=');
        sb.append(((flight.getLongitude() == null)?"<null>":flight.getLongitude()));
        sb.append('\n');
        sb.append("latitude");
        sb.append('=');
        sb.append(((flight.getLatitude() == null)?"<null>":flight.getLatitude()));
        sb.append('\n');
        sb.append("baroAltitude");
        sb.append('=');
        sb.append(((flight.getBaroAltitude() == null)?"<null>":flight.getBaroAltitude()));
        sb.append('\n');
        sb.append("velocity");
        sb.append('=');
        sb.append(((flight.getVelocity() == null)?"<null>":flight.getVelocity()));
        sb.append('\n');
        sb.append("trueTrack");
        sb.append('=');
        sb.append(((flight.getTrueTrack() == null)?"<null>":flight.getTrueTrack()));
        sb.append('\n');
        sb.append("verticalRate");
        sb.append('=');
        sb.append(((flight.getVerticalRate() == null)?"<null>":flight.getVerticalRate()));
        sb.append('\n');
        sb.append("geoAltitude");
        sb.append('=');
        sb.append(((flight.getGeoAltitude() == null)?"<null>":flight.getGeoAltitude()));
        sb.append('\n');
        sb.append("squawk");
        sb.append('=');
        sb.append(((flight.getSquawk() == null)?"<null>":flight.getSquawk()));
        sb.append('\n');
        sb.append("spi");
        sb.append('=');
        sb.append(((flight.getSpi() == null)?"<null>":flight.getSpi()));
        sb.append('\n');
        sb.append("onGround");
        sb.append('=');
        sb.append(((flight.getOnGround() == null)?"<null>":flight.getOnGround()));
        return sb.toString();
    }

    public String printFlightV3(FlightStateSchema3 flight) {

        StringBuilder sb = new StringBuilder();
        sb.append("callsign (aka FLIGHT NUMBER)");
        sb.append('=');
        sb.append(((flight.getCallsign() == null)?"<null>":flight.getCallsign()));
        sb.append('\n');
        sb.append("icao24");
        sb.append('=');
        sb.append(((flight.getIcao24() == null)?"<null>":flight.getIcao24()));
        sb.append('\n');
        sb.append("originCountry");
        sb.append('=');
        sb.append(((flight.getOriginCountry() == null)?"<null>":flight.getOriginCountry()));
        sb.append('\n');
        sb.append("timePosition");
        sb.append('=');
        sb.append(((flight.getTimePosition() == null)?"<null>":flight.getTimePosition()));
        sb.append('\n');
        sb.append("lastContact");
        sb.append('=');
        sb.append(((flight.getLastContact() == null)?"<null>":flight.getLastContact()));
        sb.append('\n');
        sb.append("longitude");
        sb.append('=');
        sb.append(((flight.getLongitude() == null)?"<null>":flight.getLongitude()));
        sb.append('\n');
        sb.append("latitude");
        sb.append('=');
        sb.append(((flight.getLatitude() == null)?"<null>":flight.getLatitude()));
        sb.append('\n');
        sb.append("baroAltitude");
        sb.append('=');
        sb.append(((flight.getBaroAltitude() == null)?"<null>":flight.getBaroAltitude()));
        sb.append('\n');
        sb.append("velocity");
        sb.append('=');
        sb.append(((flight.getVelocity() == null)?"<null>":flight.getVelocity()));
        sb.append('\n');
        sb.append("trueTrack");
        sb.append('=');
        sb.append(((flight.getTrueTrack() == null)?"<null>":flight.getTrueTrack()));
        sb.append('\n');
        sb.append("verticalRate");
        sb.append('=');
        sb.append(((flight.getVerticalRate() == null)?"<null>":flight.getVerticalRate()));
        sb.append('\n');
        sb.append("geoAltitude");
        sb.append('=');
        sb.append(((flight.getGeoAltitude() == null)?"<null>":flight.getGeoAltitude()));
        sb.append('\n');
        sb.append("squawk");
        sb.append('=');
        sb.append(((flight.getSquawk() == null)?"<null>":flight.getSquawk()));
        sb.append('\n');
        sb.append("spi");
        sb.append('=');
        sb.append(((flight.getSpi() == null)?"<null>":flight.getSpi()));
        sb.append('\n');
        sb.append("gate");
        sb.append('=');
        sb.append(((flight.getGate() == null)?"<null>":flight.getGate()));

        return sb.toString();
    }
}
